name: Mirror Minetest

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:  # Permite execução manual

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Clone minetest repository
      run: git clone --mirror https://github.com/minetest/minetest.git

    - name: Push to GitHub
      run: |
        cd minetest.git
        git remote set-url origin https://Renan2010:${{ secrets.PAT_GITHUB }}@github.com/Renan2010/minetest-mirror.git
        git push --mirror origin
